# Tensorflow2.0 小练习

In [18]:
import torch
import numpy as np


## 实现softmax函数

In [19]:
def softmax(x):
    ##########
    '''??softmax????????softmax???'''
    ##########
    x = torch.as_tensor(x, dtype=torch.float32)
    x = x - torch.max(x, dim=-1, keepdim=True).values
    x_exp = torch.exp(x)
    prob_x = x_exp / torch.sum(x_exp, dim=-1, keepdim=True)
    return prob_x


test_data = np.random.normal(size=[10, 5])
(torch.square(softmax(test_data) - torch.softmax(torch.as_tensor(test_data, dtype=torch.float32), dim=-1)) < 0.0001)


tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

## 实现sigmoid函数

In [20]:
def sigmoid(x):
    ##########
    '''??sigmoid????????sigmoid???'''
    ##########
    x = torch.as_tensor(x, dtype=torch.float32)
    prob_x = 1.0 / (1.0 + torch.exp(-x))
    return prob_x


test_data = np.random.normal(size=[10, 5])
(torch.square(sigmoid(test_data) - torch.sigmoid(torch.as_tensor(test_data, dtype=torch.float32))) < 0.0001)


tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

## 实现 softmax 交叉熵loss函数

In [21]:
def softmax_ce(x, label):
    ##########
    '''??softmax???loss???x?softmax?????'''
    ##########
    x = torch.as_tensor(x, dtype=torch.float32)
    label = torch.as_tensor(label, dtype=torch.float32)
    loss = -torch.mean(torch.sum(label * torch.log(x + 1e-12), dim=-1))
    return loss


test_data = np.random.normal(size=[10, 5])
logits = torch.as_tensor(test_data, dtype=torch.float32)
prob = torch.softmax(logits, dim=-1)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)] = 1.

(torch.square(torch.mean(torch.nn.functional.cross_entropy(logits, torch.argmax(torch.as_tensor(label), dim=1), reduction='none'))
              - softmax_ce(prob, label)) < 0.0001)


tensor(True)

## 实现 sigmoid 交叉熵loss函数

In [22]:
def sigmoid_ce(x, label):
    ##########
    '''??sigmoid???loss???x?sigmoid?????'''
    ##########
    x = torch.as_tensor(x, dtype=torch.float32)
    label = torch.as_tensor(label, dtype=torch.float32)
    loss = -torch.mean(label * torch.log(x + 1e-12) + (1.0 - label) * torch.log(1.0 - x + 1e-12))
    return loss


test_data = np.random.normal(size=[10])
logits = torch.as_tensor(test_data, dtype=torch.float32)
prob = torch.sigmoid(logits)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print(label)

(torch.square(torch.mean(torch.nn.functional.binary_cross_entropy_with_logits(logits, torch.as_tensor(label, dtype=torch.float32), reduction='none'))
              - sigmoid_ce(prob, label)) < 0.0001)


[1. 1. 1. 1. 1. 0. 0. 0. 1. 0.]


tensor(True)